version: "3"
services:   
  webinterface:
    image: liborrow-webinterface
    container_name: webinterface
    deploy:
      replicas: 1
    hostname: webinterface
    ports:
      - "80:8080"
    networks:
      - webnet

networks:
  webnet: